apiVersion: apps/v1
kind: Deployment
metadata:
  name: websocket-deploy
  namespace: production
  labels:
    app: websocket
spec:
  replicas: 3
  selector:
    matchLabels:
      app: websocket
  template:
    metadata:
      labels:
        app: websocket
    spec:
      containers:
      - name: websocket
        image: jocaloide/infra-project-websocket:1
---

apiVersion: v1
kind: Service
metadata:
  name: websocket-svc
  namespace: production
spec:
  selector:
    app: websocket
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
