apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: production
  labels:
    type: postgres
spec:
  capacity:
    storage: 200Mi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  storageClassName: local-storage
  local:
    path: /mnt
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - node-03
